### ISSUE TITLE
Error when the store contains the tag </script>

### ISSUE THREAD

**Issue by csarglue** [GlueDigital/universal-scripts#6]
When there is a element in the store that contains a tag </script>, the content of the store is displayed on the web

**Comment by mancontr** [comment]
It has been fixed in v1.2.2.
The issue was that JSON.stringify was being used to save the store contents to the "initial state" variable on the html generated on the server, but this fails if any string contains `</script>` as it would close the enclosing `<script>` tag. Now we're using [jsenc](https://github.com/mathiasbynens/jsesc) to do it instead.
